name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip        
    - name: Install hanabi dependencies
      run: |
        pip install numpy tensorflow gin-config scikit-build
    - name: install flake dependencies
      run: |
         pip install flake8
    - name: Analysing the code with flake
      run: |
        flake8 $(git ls-files '*.py')         
    - name: install pylint dependencies
      run: |
         pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
